### ISSUE TITLE
Clarifications for Hudson's algorithm analysis

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#219]
Two points from Reviewer 1:

> Reviewer Point 1.13 —
> Line 420 - Despite the long description, I was not able to follow how the previous paragraph implies that ”work is spread out relatively evenly on the coalescent time scale”
> Reviewer Point 1.14 —
> Line 422 - There is no context to what is meant by ”large” or ”small” here - is 2 or 10 or 10000 ”large”.

@petrelharp - any thoughts here?

**Comment by jeromekelleher** [comment]
@petrelharp I need your help here. I've answered the first point by deleting the sentence (it wasn't crucial to the point). I can't answer the second one though. Here's the text in question:
```
Suppose that population size today is $N_1$,
while $T$ generations ago it was $N_2$.
Does the run time depend more on $4 N_1 L$ or $4 N_2 L$?
The answer depends on how $T$ compares to $N_1$: if $T/N_1$ is large,
then run time will be similar to a population of size $N_1$;
while if $T/N_1$ is small, it will be similar to a population of size $N_2$.
```

What's a large or small value of T/N1 here?

**Comment by JereKoskela** [comment]
I'll jump in with a conjecture, completely unsupported by actual simulations, in the hope that it might be useful. Happy to be corrected by someone more informed.

N_1 should be more important if only a few lineages remain by time T. Otherwise, N_2 should be the important number.
 
The expected TMRCA of a Wright-Fisher population of size N_1 is about 2 N_1, and the majority of coalescence takes place in the first half of that time with high probability.

Hence, T/N_1 ~ 1 should be the right order of magnitude for when only a few lineages can be expected to remain by time T.

**Comment by jeromekelleher** [comment]
So, how about 

> if $T/N_1 \appox 1$ then run time will be similar to a population of size $N_1$; while if $T/N_1 \ll 1$ it will be similar to a population of size $N_2$.

**Comment by JereKoskela** [comment]
Other way around I think, unless I'm misreading things.

> If $T / N_1 \ll 1$ then the number of extant lineages remaining after $T$
> generations is likely to be substantial, and the algorithm runtime is primarily
> determined by $N_2$. Conversely, if $T / N_1 \gg 1$, then few extant
> lineages are likely to remain by time $T$ and runtime depends mainly on $N_1$.

**Comment by jeromekelleher** [comment]
Ah yes, of course. I'll put this in - @petrelharp can complain later if he disagrees!

**Comment by sgravel** [comment]
I do think that this section is a bit more confusing than it needs to be. I doubt many readers will follow the qualitative argument, and in the end we are really just saying that N_1 matters when T/N_1 is "large", which we could maybe do instead with just a bit of hand-waving and without getting into this whole argument. 

The simplest handwavy argument I can cook up quickly: 
0-Because there are about as many coalescences as recombinations, we can estimate the work by counting either coalescences or recombinations. Here I count coalescences. 
1-the amount of coalescence per generation is propto the square of the number of lineages;
2-The number of lineages left is proportional to the number of ancestral chunks left (and at least not larger than that!)
3-The number of ancestral chunks decays exponentially over time, at the same rate as the amount of ancestral material left;
4- Thus very little work is done for t/2N>10.  

We could formalize this by estimating the number of remaining chunks at any time t as S \simeq  L t Exp[-\alpha t/ 2N], where \alpha simeq 0.5 is a numerical fudge factor (there may be an exact value for it). The number of lineages left is not larger than the number of chunks, but is probably not much smaller, so we can estimate and bound the number of coalescences occurring per generation is order S^2/2N ~
L^2 t^2 Exp[-alpha t / 2N].

So the total number of coalescences, which is a good proxy for total amount of work, is the sum of this over all times, \int_0^\infty L^2 t^2 Exp[-alpha t / 2N] dt = 8 \rho^2. 

To get an estimate over a changing demography, we could simply ask how far back do we have to change the population size to have done half the work. That is an easy numerical integral (it's like 4 N1).  

I could formalize this a bit, but don't know if you want to add more possibly criticizable stuff.

**Comment by jeromekelleher** [comment]
Looks good to me @sgravel, and I have no objection to making this change. Let's see what @petrelharp says when he gets back.
