### ISSUE TITLE
Sentence in introduction warning about neutral simulations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#228]
For reviewer 3. Can be more than one sentence. Ideally pithily saying that while neutral sims are useful, they are an approximation and there will be many situtations in which they are a bad approximation (with some refs).

**Comment by grahamgower** [comment]
I wonder if reviewer 3 is an author on the recent "you must include background selection" manuscript: https://www.biorxiv.org/content/10.1101/2021.10.27.466171v1

**Comment by gregorgorjanc** [comment]
@jeromekelleher maybe cite the paper that @grahamgower just mentioned?!

**Comment by jeromekelleher** [comment]
Yes, that sounds perfect. Hadn't seen that preprint, quite the author lineup.

**Comment by mufernando** [comment]
echoing @sgravel comment elsewhere that we should also emphasize how even forward-in-time simulations rely on msprime to do the recapitation!!

**Comment by andrewkern** [comment]
i think the response to the reviewer in the response document is perfect. i didn't see an additional sentence in the intro (at least in looking at the diff) however. i'll offer on in a separate PR

**Comment by andrewkern** [comment]
offered up an option in #230

**Comment by sgravel** [comment]
For the intro sentence, we could simply add the following to recognize the limitations of the coalescent upfront: 

The coalescent is an efficient framework for population genetic simulation **under neutrality or simplified selection models**, because it allows us to simulate the genetic ancestry for a sample 68 from an idealised population model, without explicitly representing the population in memory or 69 stepping through the generations. 

Or, in the last intro paragraph, something like:

"Through a rigorous open-source community development process, msprime has gained a large number of features since its introduction, making it a highly efficient and flexible platform for population genetic simulation. **While the coalescent approach limits the types selection models that can be implemented directly in msprime, the new features and new interface enabling integration with forward simulators will facilitate the exploration of a wider range of evolutionary effects at scale.

**Comment by sgravel** [comment]
Oooh, ooh, how about:
 "Because coalescent approaches remain limited in the types of selection and mating patterns they can account for, not all biologically relevant models can be implemented in msprime [see e.g.,  Johri preprint :)].  However, the new features and new interface enabling integration with forward simulators will facilitate the exploration of a wider range of evolutionary effects at scale."

**Comment by jeromekelleher** [comment]
This is very nice @sgravel! Have you seen the updates in #232, though? I think I'll merge that and we can iterate from there.

**Comment by sgravel** [comment]
I did not, got sidetracked googling « eeyore ». What you have looks great.
