### ISSUE TITLE
Unpack "extensible" a bit?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime-1.0-paper#46]
The paper title included the word "extensible", but I'm not quite sure what that means in this context: do we mean that people can join the dev team and add features, or we provide some sort of plug-in methodology, or that we can use tskit as an interchange format, or quite what? I think if this word is to be used in the title it needs a little more explanation - it's currently only mentioned in 2 other places in the text.

**Comment by hyanwong** [comment]
I think this could be unpacked by a sentence or two in the "Development model" subsection?

**Comment by jeromekelleher** [comment]
Good point. I think of it as extensible in a few ways:

1. We have an open source community development model which encourages people to add new features. 
2. By being based on the backwards-time coalescent process, new processes are easily added in because we can think of them as competing exponentials. In principle all we need is the waiting time until the next event and a function to apply that event, and we don't have to alter the other processes in any way. This is contrasted with left-to-right/SMC approaches, where every process has to be carefully modelled with new theory developed.
3. We have an AncestryModel architecture which lets us develop new models, relatively independently of the others (in principle one could imagine a plugin system of some sort, but that would be a msprime 2.0 feature)

Not sure how these will be brought into the narrative, but they'll fit in somewhere. Possibly "extensible" doesn't belong in the title, though.

**Comment by jeromekelleher** [comment]
Closing this, as the title won't include "extensible"
